version: '3'

services:
  streaming_service:
    build:
      context: ./recorder
    expose:
      - "5000"
    devices:
      - /dev/video0:/dev/video0

  telegram_service:
    build:
      context: ./telegram
    volumes:
      - ./yolov5:/app/yolov5

  yolov5_service:
    build:
      context: ./yolov5
    volumes:
      - ./yolov5:/app
    depends_on:
      - streaming_service